on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: build
        run: |
          sudo apt-get update
          
          npm install
          npm install firebase
          npm install -g firebase-tools
          npm run build
          
          # todo: find a way to authenticate here, like firebase login
          firebase init hosting
          firebase deploy --only hosting:felix-xyz
