on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Build and deploy
        run: |
          sudo apt-get update
          npm install
          npm install firebase
          npm install -g firebase-tools@12.5.0
          npm run build
          firebase deploy --only hosting:felix-xyz
